### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Naxon** [petehouston/laravel-deploy-on-shared-hosting#1]
Hi,

After installing Laravel 5 using your tutorial, I get a "Internal Server Error".
Installation address: http://naxon.co.il/

**Comment by petehouston** [comment]
What is the server log saying?

**Comment by Naxon** [comment]
apache error_log

[Tue Mar 29 22:52:44 2016] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Mar 29 22:52:44 2016] [notice] Digest: generating secret for digest authentication ...
[Tue Mar 29 22:52:44 2016] [notice] Digest: done
[Tue Mar 29 22:52:44 2016] [notice] Apache/2.2.15 (Unix) DAV/2 configured -- resuming normal operations
[Tue Mar 29 22:54:30 2016] [notice] caught SIGTERM, shutting down
[Tue Mar 29 22:54:30 2016] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Mar 29 22:54:30 2016] [notice] Digest: generating secret for digest authentication ...
[Tue Mar 29 22:54:30 2016] [notice] Digest: done
[Tue Mar 29 22:54:30 2016] [notice] Apache/2.2.15 (Unix) DAV/2 configured -- resuming normal operations
[Tue Mar 29 22:54:48 2016] [notice] caught SIGTERM, shutting down
[Tue Mar 29 22:54:55 2016] [notice] suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Tue Mar 29 22:54:55 2016] [notice] Digest: generating secret for digest authentication ...
[Tue Mar 29 22:54:55 2016] [notice] Digest: done
[Tue Mar 29 22:54:55 2016] [notice] Apache/2.2.15 (Unix) DAV/2 configured -- resuming normal operations
[Tue Mar 29 22:56:01 2016] [notice] caught SIGTERM, shutting down

**Comment by petehouston** [comment]
The log doesn't tell anything related to Laravel. Please checkout `/storage/logs/laravel.log`

**Comment by Naxon** [comment]
logs folder is empty

**Comment by petehouston** [comment]
It looks like your have problems with Apache server configuration. Just try with a single html file to see whether Apache works, then retry my steps from tutorials.

**Comment by Naxon** [comment]
an html file worked fine before I tried the tutorial

**Comment by petehouston** [comment]
send me the server information to my email address, I will take a look at your issue.

**Comment by Naxon** [comment]
> [08-Apr-2016 11:41:58 Europe/Helsinki] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_mbstring.dll' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_mbstring.dll: cannot open shared object file: No such file or directory in Unknown on line 0
> [08-Apr-2016 11:41:58 Europe/Helsinki] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_openssl.dll' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_openssl.dll: cannot open shared object file: No such file or directory in Unknown on line 0
> [08-Apr-2016 11:42:13 Europe/Helsinki] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_mbstring.dll' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_mbstring.dll: cannot open shared object file: No such file or directory in Unknown on line 0
> [08-Apr-2016 11:42:13 Europe/Helsinki] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_openssl.dll' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_openssl.dll: cannot open shared object file: No such file or directory in Unknown on line 0

Here is the log. The specified folder only contains pdo_sqlite.so, pdo_mysql.so and pdo.so.

**Comment by petehouston** [comment]
It looks like your PHP configuration is so incorrect. On Linux, shared library has `.so` extension, not `.dll`.
