### ISSUE TITLE
Storage_path(): Cannot access my local storage, it is showing a broken link

### ISSUE THREAD

**Issue by JamieBunyassi** [petehouston/laravel-deploy-on-shared-hosting#10]
Everything is working on my end except accessing the files via the storage_path() helper. I noticed that when I uploaded my application that the shortcut that links to the storage file from the public folder was missing. Perhaps this is, in part, the problem. Also I did not follow your steps and I was able to get the pages to display by simply copying the app folder in the public_html and linking to it via .htaccess.

**Comment by petehouston** [comment]
@JamieBunyassi files in `storage` are not supposed to be seen publicly. To expose files inside `storage/app` you need to:
- First, setup the permission `$ chmod -R 755 storage/app` 
- Second, create a symbol link to `public` for example, `$ ln -s path/to/project/storage/app path/to/project/public/storage`.

https://laravel.com/docs/5.3/structure#the-storage-directory

**Comment by JamieBunyassi** [comment]
It worked but when I try to access the symbolic link it says 

> too many levels of symbolic links 

any ideas why?

**Comment by petehouston** [comment]
@JamieBunyassi it looks like you create a looped symbol link. Make sure target directory, which is symbol-linked, there is no other symbol link inside that refers to outside.

**Comment by JamieBunyassi** [comment]
Just checked and there are no symbolic links inside the directories. Here is the command I am running from the application's main directory...

>  ln -s storage/app/public public/storage

It maybe useful to say that the main point of all this is to upload files to shared hosting and although my code is working locally it is not doing so on the hosting service. Also not to mention it takes like 100 years to upload a small file to the hosting service. Here is my code 

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Video;

use App\Http\Requests;

use Illuminate\Support\Facades\Storage;

use Image;

use Auth;

class VideoUploadController extends Controller
{
    public function index()
    {
        return view('VideoUpload');
    }

    public function store(Request $request, Video $video)
    {
        $uid = uniqid(1);

        $user = $request->user();

        $filename = $uid . '.' .'mp4';

        $storagePath = $request->video->storeAs('public', $filename);

        if($request->hasFile('avatar')){
            $avatar = $request->file('avatar');
            $bio = $request->bio;
            $avatar_name = time() . '.' . $avatar->getClientOriginalExtension();
            Image::make($avatar)->resize(300, 400)->save( public_path('/images/avatars/' . $avatar_name)); 
            $user->avatar = $filename;
            $user->bio = $bio;
            $user->save();

            $video = $user->videos()->create([
                'uid' => $uid,
                'title' => $request->title,
                'description' => $request->description,
                'thumbnail' => $avatar_name,
                'video_filename' => $filename,
                ]); 
        }
        return redirect('/videos');
    }
}
```

This is just to give you more insight on the problem.

**Comment by petehouston** [comment]
Look at these lines:

```
$storagePath = $request->video->storeAs('public', $filename);

Image::make($avatar)->resize(300, 400)->save( public_path('/images/avatars/' . $avatar_name)); 
```

At top you saved file to `storage/app/public` which is config in `public` driver, but second line saves file in `public/images...`.  This is wrong path because the symlink map to `public/storage`, isn't it?

Secondly, the symbol link command is typically incorrect.

```
$ ln -s storage/app/public public/storage
```

You have to specify absolute path, not relative path while making symbol link.
