### ISSUE TITLE
Internal Server Error (/public/.htaccess: Options not allowed here)

### ISSUE THREAD

**Issue by chiscojfr** [petehouston/laravel-deploy-on-shared-hosting#18]
Hi, 
After installing Laravel 5.2 using your tutorial, I get a "Internal Server Error".

"Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log."

The log has te following error: /public/.htaccess: Options not allowed here

**Comment by petehouston** [comment]
You should check server log or contact server admin.

If you have permissions, I guess it's probably because of your file permission mode, and you might to set to `0644` or equivalent.
