### ISSUE TITLE
 Error upload project laravel 5.3 to share hosting

### ISSUE THREAD

**Issue by phamquoclk** [petehouston/laravel-deploy-on-shared-hosting#21]
Your website upload to shared hosting is wrong, laravel 5.3:

InvalidArgumentException in FileViewFinder.php line 137:
View [front.home_page.index] not found.

Pleased help me! .. host share  not use the command line

**Comment by petehouston** [comment]
It's your code problem. Put `index.php` into `views/front/home_page` directory.

**Comment by mariapaulinar** [comment]
I have the same error. I already verified that the view exists in the resources / views directory. My hosting is A2 Hosting :(
