### ISSUE TITLE
I just used GeekStorage's Framework to install Laravel, but?

### ISSUE THREAD

**Issue by RFMyr** [petehouston/laravel-deploy-on-shared-hosting#24]
Hello,

On my GeekStorage cPanel, I scrolled down to "Categories" at the bottom, clicked on "Frameworks", then clicked on the Laravel icon and installed version 5.4.23.  However, I had to install it in the public folder, I couldn't specify a folder on the same level as the public folder.  Perhaps I should have put in "../Laravel" as the install folder rather than "Laravel", but at the time, I wasn't sure exactly where it would be installed.  After installing it, I found that it created the Laravel folder in the public folder and installed Laravel in that folder.

That bothered me as my research indicated that it should be on the same level as the public folder for security reasons.  So, after installing it, I did more research and found your post, to which this is a reply to.

Should I uninstall the Laravel installed by the cPanel framework described above and install it as you have described?  Or perhaps try using "../Laravel" to see of that works from the Framework install process?

Thanks for sharing your work on the matter.

**Comment by petehouston** [comment]
Yeah, I guess so. By default, the software installation provided by cPanel will setup in your hosting account `public` directory, which is very insecure, especially in case of Laravel app.

So I think you'd better try to upload Laravel `public` folder to hosting `public` (or, `www`, or `public_html`...) folder, and other Laravel's folders and files into hosting account, usually at `/home/USER_ACCOUNT`. Make sure to change directory path in some Laravel files like `bootstrap.php`, `index.php` ... as mentioned in the guide.
