### ISSUE TITLE
Deployment - 500 Internal Server Error

### ISSUE THREAD

**Issue by milesthom** [petehouston/laravel-deploy-on-shared-hosting#26]
Hi Pete,

You very generously offered to provide some guidance if a Laravel deployment did not work. Unfortunately mine is not., returning a "500 Internal Server Error" 

The domain is portfolio.eastportprop.com. The hosting company uses ```/public``` for web pages, and that has been tested with  a "Hello World" index.html that has displayed correctly.

The directory structure is as follows:
```
/
--public
--laravel (rather than "project" as you suggested in your deployment instructions.
```
Everything except the .env file has been copied from the ```/laravel/public``` directory to ```/public```.

All other project files remain in the ```/laravel``` directory.
I did not delete ```/laravel/public```.

Modifications to ```/public/index.php``` have been made as follows:
```
require __DIR__.'/../laravel/bootstrap/autoload.php';
$app = require_once __DIR__.'/../laravel/bootstrap/app.php';
```
And to /laravel/server.php:
```
require_once __DIR__.'../public/index.php';
```
The .htaccess file is very simple:
--- start of file ---
```
Options +FollowSymLinks
AddType image/jpeg .jpeg .jpg .jpe .JPG 
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
```
--- end of file ---

There is a .htpasswd file in /public leftover from a previous PHP Cake installation.

The server is Apache and I have verified that the PHP version 5.6.30. Unfortunately the hosting co has blocked phpinfo(). 

There is no command line PHP, so I have not been able to run the Composer commands in your instructions.

The MySQL database is operating and I can manually execute queries against it.

Any suggestions or guidance you can offer will be welcomed.

Regards - Miles Thompson

Error message:
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, or webmaster and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

**Comment by TanjillaTina** [comment]
change these to:
$app = require_once __DIR__.'/bootstrap/app.php';
require __DIR__.'/bootstrap/autoload.php';
then bring out the public folder's all files and sub folders to the publichtml file,
after that change the routes, then add the dbname and username to the .env file.
then try to run it, it will work.

**Comment by milesthom** [comment]
Hi TanjillaTina,

Thank you for the suggestions. 

Are you suggesting that those **DIR** paths be hard-coded?

All of the contents of the app's public folder have been moved to the public html directory.

Why change the routes?

The .env file has been updated with the database information.

Cheers - Miles

**Comment by milesthom** [comment]
The Rogers server team worked out a solution, once I explained to them how Laravel works, by adding this line to .htaccess

```
RewriteBase /
```

And it worked!
