### ISSUE TITLE
Second/Third time deployment

### ISSUE THREAD

**Issue by yammadev** [petehouston/laravel-deploy-on-shared-hosting#28]
Hello there,

I followed the steps and it worked as expected. Now the thing is, what is the procedure when deploying for the second/third time?  

Regards,

**Comment by petehouston** [comment]
Nothing much, just copy code files and avoid overwrite the `public/index.php`.

**Comment by yammadev** [comment]
Thanks for the reply. This is not intended to be used in zero downtime deployment, right?
