### ISSUE TITLE
Not Working on NameCheap

### ISSUE THREAD

**Issue by jmoiz11** [petehouston/laravel-deploy-on-shared-hosting#3]
Hello - I am using Namecheap shared hosting and followed your directions step by step, I did not receive any errors during the set up, but am receiving a 404 error - where page cannot be found.
A few questions:
-What does the .htaccess file look like in your laravel project folder?
-What does the .htaccess file look like in your www/public/ folder ?
-Are you copying/modifying the php.ini file in the laravel project folder, or in the www/public folder?

-Are you changing the paths in index.php, in the www/public/ folder - especially for the following:

require **DIR**.'/../bootstrap/autoload.php';

$app = require_once **DIR**.'/../bootstrap/app.php';

Thanks for your help!

**Comment by jmoiz11** [comment]
I solved the issue - there are 2 items missing from the tutorial - one is make sure the .htaccess file is correct, i.e. redirections are configured properly.
Two - make sure to change the public/index.php file for the following 2 lines to reflect the correct paths:

require **DIR**.'/../bootstrap/autoload.php';
$app = require_once **DIR**.'/../bootstrap/app.php';

**Comment by petehouston** [comment]
@jmoiz11 the `.htaccess` file is the default one :), also I updated the inclusion part in `index.php`. Thanks.

**Comment by oluebubesyd** [comment]
@jmoiz11 can I see a correct sample of a .htaccess file?

I'm having the same issues after installation.  My page links are not working (returning a 404) and assets like css, img and js arent being pulled in
