### ISSUE TITLE
Laravel Deployment issue

### ISSUE THREAD

**Issue by SallmanRafi** [petehouston/laravel-deploy-on-shared-hosting#34]
I have uploaded my website but getting this error
Parse error: syntax error, unexpected '?' in /home/arslanbrothers/laravel50/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 500
and on line 500
return $factory->of($arguments[0], $arguments[1])->times($arguments[2] ?? null);

**Comment by petehouston** [comment]
What is your Laravel version and PHP version?

**Comment by SallmanRafi** [comment]
laravel 5.8.28

**Comment by petehouston** [comment]
Can you share your `composer.json`?

**Comment by nelson6e65** [comment]
Seems to be a PHP version issue.
[Null coalescing operator](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op) is a php 7.0 feature. Are you sure you are you using PHP 7?

**Comment by SallmanRafi** [comment]
php 5.6

**Comment by nelson6e65** [comment]
Well... You need to setup your server to use PHP 7.1.3+, as required by Laravel 5.8:
https://laravel.com/docs/5.8#server-requirements

**Comment by SallmanRafi** [comment]
that’s it? only because of this issue, my website is not getting uploaded
on server?

**Comment by nelson6e65** [comment]
Yes. You can use Laravel 5.4, which is compatible with PHP 5.6, but is ***extremely*** not recommended, because has reached its end of life: https://www.php.net/supported-versions.php

Only PHP 7.1+ are supported at this time by PHP team and your hosting should have that version available.

**Comment by SallmanRafi** [comment]
Thank You Sir
I’ll work on it
If got any error, may I disturb you again?

**Comment by SallmanRafi** [comment]
What to do now

**Comment by petehouston** [comment]
@SallmanRafi  updating PHP issue?

**Comment by SallmanRafi** [comment]
Sir can you please guide me the complete procedure from very beginning?

**Comment by nelson6e65** [comment]
@SallmanRafi Once you test your app runs locally and your hosting fits the Laravel and your app requirements, you can follow the generic instructions in the README.md file.

If you are having more troubles _after_ follow that instructions, you should explain (in details) what problems you have.

Take in consideration that this instructions are more directed to previous PHP/Laravel versions, so we need more specific details of the issues you have. 😅

**Comment by SallmanRafi** [comment]
I already have a website on my cpanel but its in core php. So I developed a new website in laravel. Now website is complete and I want to upload it in my cpanel. But I want to use both the websites, the previous one and this one. I wanna do this just because if my new website gets any error, previous one should be there as a backup. Once I get to know that my new website is totally error free I will remove my previous website from cpanel.
