### ISSUE TITLE
Assets not being loaded !

### ISSUE THREAD

**Issue by slicinga** [petehouston/laravel-deploy-on-shared-hosting#4]
I followed the steps quite thoroughly and the site is loaded but without its assets (css, javascript and images). Is there anything else that I should take care not included in your steps ?

**Comment by slicinga** [comment]
By the way I am in Godaddy and the directory structure is same as you have given.

**Comment by petehouston** [comment]
how do you load css, js, images...in your code?

**Comment by slicinga** [comment]
Most of them are loaded directly embeded like this:
<link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>

Is that the cause ?

**Comment by slicinga** [comment]
But it doesnt work even I tried with
{!! Html::style('assets/plugins/bootstrap/css/bootstrap.min.css') !!}
        {!! Html::style('assets/plugins/font-awesome/css/font-awesome.min.css') !!}
        {!! Html::style('assets/plugins/et-line/et-line.css') !!}

I get the error message as 
Page Not Found
Sorry, but the page you were trying to view does not exist.

Can you please help me to resolve the issue ? I am not good at server handling.

Thanks in advance.

**Comment by slicinga** [comment]
We managed now by copying all the assets to ~/www directory. Every time when we do git pull, we have to copy the files to www. So would like to see the permanent solution of it.

**Comment by petehouston** [comment]
@slicinga just create a symbol link from your project `public`.

```
$ ln -s ../path/to/project/public /home/username/www
```
