### ISSUE TITLE
error link 

### ISSUE THREAD

**Issue by iamseye** [petehouston/laravel-deploy-on-shared-hosting#6]
Hi,Thanks for article. But i didnt get it work.

I followed this tutorial https://medium.com/laravel-news/the-simple-guide-to-deploy-laravel-5-application-on-shared-hosting-1a8d0aee923e#.3ut5qhmh5 
to deploy  my project on Godaddy. 

I created a 'hjproject' folder on the same level as public_html, then link hjporject/public to www with 
ln -s /hjproject/public  /www

But it didnt work and I got 500 error.

Then I deleted hjproject, and followed this tutorial https://github.com/petehouston/laravel-deploy-on-shared-hosting

So I created a 'project' folder and clone my hjproject into the 'project' folder. Then link project/hjporject/public to www with
ln -s ~/www public  as the article said.

Then I opened myapp.com , it changed to myapp.com/hjproject/public and showed 'Sorry, the page you are looking for could not be found.'
It seems used the old connection ? but even i connect to myapp.com/project/hjproject/public , it showed the same.

Thanks in advance !

**Comment by petehouston** [comment]
@iamseye 500 error indicates that you've not configured project properly, it could be:
- no security key found?
- no appropriate permission for `storage`?
- file config or `.env` not found?
- DB misconfigured?
- ...

Also, for symbol-link in GoDaddy, please you absolute path.

Please open `storage/logs/laravel.log` for detail information about error.

**Comment by iamseye** [comment]
Hi @petehouston , thank you for replying.

But it't not 500 error now, just showed Sorry, the page you are looking for could not be found. 

sorry, how can I checked security key?
I used ssh login the server in godaddy and git clone from my git

my storage got 777 permission
and I did lose .env file sorry, after I added it , still got same problem

There's an error showed in laravel.log

```
[2016-08-30 05:24:35] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /home/hechiun/project/hjproject/bootstrap/cache/compiled.php:7772
Stack trace:
```

here's the directory in /home/hechiun/project/hjproject

```
drwxr-xr-x 13 hechiun hechiun    4096 2016-08-29 23:30 ./
drwxrwxr-x  3 hechiun hechiun    4096 2016-08-29 20:11 ../
drwxrwxr-x 10 hechiun hechiun    4096 2016-08-29 20:11 app/
-rw-rw-r--  1 hechiun hechiun    1646 2016-08-29 20:11 artisan
drwxrwxr-x  3 hechiun hechiun    4096 2016-08-29 20:11 bootstrap/
-rw-rw-r--  1 hechiun hechiun    1315 2016-08-29 20:11 composer.json
-rw-rw-r--  1 hechiun hechiun  121165 2016-08-29 20:11 composer.lock
-rw-rw-r--  1 hechiun hechiun 1706284 2016-08-29 10:38 composer.phar
drwxrwxr-x  2 hechiun hechiun    4096 2016-08-29 20:11 config/
drwxrwxr-x  5 hechiun hechiun    4096 2016-08-29 20:11 database/
-rw-r--r--  1 hechiun hechiun     451 2016-08-29 23:30 .env
-rw-rw-r--  1 hechiun hechiun     416 2016-08-29 20:11 .env.example
drwxrwxr-x  8 hechiun hechiun    4096 2016-08-29 20:11 .git/
-rw-rw-r--  1 hechiun hechiun      61 2016-08-29 20:11 .gitattributes
-rw-rw-r--  1 hechiun hechiun      73 2016-08-29 20:11 .gitignore
-rw-rw-r--  1 hechiun hechiun     588 2016-08-29 20:11 gulpfile.js
drwxrwxr-x  4 hechiun hechiun    4096 2016-08-29 20:11 .idea/
-rw-rw-r--  1 hechiun hechiun     212 2016-08-29 20:11 package.json
-rw-rw-r--  1 hechiun hechiun    1026 2016-08-29 20:11 phpunit.xml
lrwxrwxrwx  1 hechiun hechiun      17 2016-08-29 20:13 public -> /home/hechiun/www/
drwxrwxr-x  6 hechiun hechiun    4096 2016-08-29 20:11 public_bak/
-rw-rw-r--  1 hechiun hechiun    1918 2016-08-29 20:11 readme.md
drwxrwxr-x  5 hechiun hechiun    4096 2016-08-29 20:11 resources/
-rw-rw-r--  1 hechiun hechiun     567 2016-08-29 20:11 server.php
drwxrwxrwx  5 hechiun hechiun    4096 2016-08-29 20:11 storage/
drwxrwxr-x  2 hechiun hechiun    4096 2016-08-29 20:11 tests/
drwxrwxr-x 32 hechiun hechiun    4096 2016-08-29 20:24 vendor/
```

and  in /home/hechiun/www : 

```
drwxr-x---  7 hechiun nobody  4096 2016-08-29 21:25 ./
drwx--x--x 17 hechiun hechiun 4096 2016-08-29 23:27 ../
-rw-r--r--  1 hechiun hechiun 1699 2016-08-04 16:07 404.shtml
drwxr-xr-x  2 hechiun hechiun 4096 2016-08-28 20:20 cgi-bin/
drwxrwxr-x  3 hechiun hechiun 4096 2016-08-29 07:04 css/
-rw-rw-r--  1 hechiun hechiun    0 2016-08-29 20:11 favicon.ico
-rw-r--r--  1 hechiun hechiun 1963 2016-08-04 16:07 home.html
-rw-r--r--  1 hechiun hechiun  553 2016-08-29 21:25 .htaccess
-rw-rw-r--  1 hechiun hechiun  682 2016-08-29 20:11 ie10-viewport-bug-workaround.js
drwxrwxr-x  2 hechiun hechiun 4096 2016-08-29 07:04 images/
drwxrwxr-x  4 hechiun hechiun 4096 2016-08-29 07:04 img/
-rw-rw-r--  1 hechiun hechiun 1822 2016-08-29 20:17 index.php
drwxrwxr-x  2 hechiun hechiun 4096 2016-08-29 07:04 js/
-rw-r--r--  1 hechiun hechiun 4282 2016-08-04 16:07 layout-styles.css
lrwxrwxrwx  1 hechiun hechiun   16 2016-08-29 07:53 public -> hjproject/public
-rw-rw-r--  1 hechiun hechiun   24 2016-08-29 20:11 robots.txt
-rw-rw-r--  1 hechiun hechiun  914 2016-08-29 20:11 web.config
```

and when i type myapp.com it turned to  myapp.com/hjproject/public 
is that should be alright ??

Thanks and sorry its my first laravel project so i dont know a lot

**Comment by petehouston** [comment]
@iamseye run

```
$ php artisan key:generate
```

then try again

**Comment by iamseye** [comment]
it generate the key. 
so  should I update this key in .env file?
it seems the different key in .env

**Comment by petehouston** [comment]
it generates a `valid` security key for project. So did it work?

**Comment by iamseye** [comment]
it generated the key, and i updated in .env file
but when i type myapp.com it still same

**Comment by petehouston** [comment]
@iamseye check `storage/logs/laravel.log` for different error message.

**Comment by iamseye** [comment]
it only got same error happened 3 times

**Comment by petehouston** [comment]
what is the value of `cipher` property in `config/app.php`?

**Comment by iamseye** [comment]
'cipher' => 'AES-256-CBC',

**Comment by petehouston** [comment]
try this:

```
'cipher' => MCRYPT_RIJNDAEL_128,
```

**Comment by iamseye** [comment]
it's still same

**Comment by iamseye** [comment]
is that when I type myapp.com then transfer to myapp.com/hjproject/public > that is correct??

**Comment by petehouston** [comment]
@iamseye nope. Just `myapp.com`.

Send me contact detail to my mail, I will have a look at it if no problem `contact@petehouston.com`.

**Comment by iamseye** [comment]
For sure!
already sent it ! Big thanks !!

**Comment by petehouston** [comment]
It's done, your config is wrong,

```
'cipher' => 'MCRYPT_RIJNDAEL_128',
```

It must be without single quote,

```
'cipher' => MCRYPT_RIJNDAEL_128
```

**Comment by iamseye** [comment]
Thanks a lot !! 

I really appreciate for that !!! 

Thank you so much!!
