### ISSUE TITLE
Unable to deploy Laravel App - TLS version lessthan 1.0.1

### ISSUE THREAD

**Issue by safiahmed4cs** [petehouston/laravel-deploy-on-shared-hosting#7]
Hi

I am trying to deploy my Laravel App 5.3 to shared hosting server

PFA for error which i am gettings.

As there is no option to upgrade the TLS 0.9 to 1.0.1 version as the composer needs minimum 1.0.1 

![a60e3729-4cfd-4d13-9231-4c7946fcfb63](https://cloud.githubusercontent.com/assets/13968621/19407519/a7f0d064-92ad-11e6-8c5f-be1f8ba2cfad.jpg)

**Comment by petehouston** [comment]
@safiahmed4cs it is your server configuration. please ask your service provider to update OpenSSL packages.
