### ISSUE TITLE
Constantly 404 error

### ISSUE THREAD

**Issue by marko-mlinarevic** [petehouston/laravel-deploy-on-shared-hosting#9]
can you look at mine I tried everything you wrote. it's constantly 404

Not Found

The requested URL [url/path] was not found on this server. I have gone trough your manual but it's always the same

This is from my laravel log file

`H:\OfirSpecial\knexMaster\system\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 H:\OfirSpecial\knexMaster\system\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 H:\OfirSpecial\knexMaster\system\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 H:\OfirSpecial\knexMaster\system\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 H:\OfirSpecial\knexMaster\system\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 H:\OfirSpecial\knexMaster\system\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#41 H:\OfirSpecial\knexMaster\system\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#42 H:\OfirSpecial\knexMaster\system\server.php(21): require_once('H:\\OfirSpecial\\...')
#43 {main}  
`

**Comment by petehouston** [comment]
It looks like you're using Windows server.

404 means **NOT FOUND**, so did you define **url/path** in `routes.php`?

**Comment by marko-mlinarevic** [comment]
My localhost is windows but I'm transfering it to ubuntu server. And for some reason it still pulls routes from my localhost

**Comment by petehouston** [comment]
@mlinko clear cache and dump new one?

**Comment by marko-mlinarevic** [comment]
Now I getting error 500 
it says
[url]  is currently unable to handle this request.
HTTP ERROR 500

**Comment by petehouston** [comment]
@mlinko check details in `storage/laravel.log` file
